#Mongo 配置文件

[Mongo]
    [Mongo.ShenbianUgc]
    Host = "mongo12313"
    Port = "3306"
    Name = "shenbian_ugc"
    User = "root"
    Password = "6661623616"
    charset = "utf8mb4"
    MaxOpenConns = 100
    MaxIdleConns = 10
    ConnMaxLifetime = 1